<?php
$sql_host = getenv('DB_HOST');
$sql_username = getenv('MYSQL_USER');
$sql_password = getenv('MYSQL_PASSWORD');
$sql_ro_username = getenv('RO_USERNAME');
$sql_ro_password = getenv('RO_PASSWORD');
$bounce_host = getenv('BOUNCE_HOST');
$cookie_host = getenv('COOKIE_HOST');
$redis_host = getenv('REDIS_HOST');
$redis_port = getenv('REDIS_PORT');
$redis_password = getenv('REDIS_PASSWORD');
$p2f_address[] = null;
?>
